version: '3'
services:
   web:
      image: ruslanguns/lampapp:2.0
      container_name: myapp
      restart: always
      ports:
        - "2201:22"
        - "8055:80"
        - "3308:3306"
      volumes:
        - myapp-db-data:/var/lib/mysql
        - myapp-bridge:/root
        - myapp-httpd:/var/www/myapp/public_html
volumes:
    myapp-db-data:
    myapp-bridge:
    myapp-httpd:
